
export const FETCH_PLAYLISTS = "FETCH_PLAYLISTS";
export const FETCH_PLAYLISTS_SUCCESS = "PLAYLISTS_FETCH_SUCCESS";
export const FETCH_PLAYLISTS_ERROR = "PLAYLISTS_FETCH_ERROR";

export const FETCH_WHOAMI = "FETCH_WHOAMI";
export const FETCH_WHOAMI_SUCCESS = "WHOAMI_FETCH_SUCCESS";
export const FETCH_WHOAMI_ERROR = "WHOAMI_FETCH_ERROR";
