export const FETCH_PLAYLISTS = "FETCH_PLAYLISTS";
export const FETCH_PLAYLISTS_SUCCESS = "PLAYLISTS_FETCH_SUCCESS";
export const FETCH_PLAYLISTS_ERROR = "PLAYLISTS_FETCH_ERROR";

export const FETCH_PLAYLIST = "FETCH_PLAYLIST";
export const FETCH_PLAYLIST_SUCCESS = "PLAYLIST_FETCH_SUCCESS";
export const FETCH_PLAYLIST_ERROR = "PLAYLIST_FETCH_ERROR";

export const UPDATE_PLAYLIST_TRACK_ORDER = "UPDATE_PLAYLIST_TRACK_ORDER";
export const DELETE_PLAYLIST_TRACK = "DELETE_PLAYLIST_TRACK";

export const FETCH_WHOAMI = "FETCH_WHOAMI";
export const FETCH_WHOAMI_SUCCESS = "WHOAMI_FETCH_SUCCESS";
export const FETCH_WHOAMI_ERROR = "WHOAMI_FETCH_ERROR";
